# Generated by Django 2.0.9 on 2018-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('middle', 'middle'), ('low', 'low')], default='low', max_length=10),
        ),
    ]
